### ISSUE TITLE
Insufficient Access Rights

### ISSUE THREAD

**Issue by ionelanton** [glauth/glauth#83]
Hello,
I'm trying to connect to the LDAP server using Active Directory Explorer with one of the users provided in the config files and I'm having the following error:
**handleSearchRequest error LDAP Result Code 50 "Insufficient Access Rights": Search Error: Anonymous BindDN not allowed**
What do I need to do?
Thank you!

**Comment by travisgroth** [comment]
I think this was fixed in #75 but never merged in.  @benyanke any chance that can be re-opened and merged?  I just tried it locally and it does fix functionality with sssd.

**Comment by xChapx** [comment]
Got the same issue, did you found any work around @ionelanton  ?

**Comment by anoma** [comment]
https://github.com/glauth/glauth/pull/75 was closed without comment but the issue it solved still persists.

Has this PR been rejected or just lost in time?

**Comment by travisgroth** [comment]
The original author probably deleted their fork or branch and it got auto-closed.  

I'd be willing to recreate - it seems like @butonic has taken over?

**Comment by ferventcoder** [comment]
Would love to see this get fixed. This seems like it would be a great tool for setting up lightweight LDAP for testing purposes.

**Comment by mildred** [comment]
I'm getting the same error with Cyrus SASL client. it seems Cyrus SASL binds with an empty DN as evidenced in its code:

https://github.com/cyrusimap/cyrus-sasl/blob/0189425cc210555c36383293c468df5da73acc48/plugins/ldapdb.c#L117

The second parameter to `ldap_sasl_interactive_bind_s` is the bind dn, no ? I'm not entirely sure but it seems so. And because it is NULL, it seems that the bind dn is empty.

A bit later in the code, the LDAP client asks whoami on the connection, does it fills in a bind dn for future requests ?

https://github.com/cyrusimap/cyrus-sasl/blob/0189425cc210555c36383293c468df5da73acc48/plugins/ldapdb.c#L126

**Comment by Hellhium** [comment]
After a bit of investigation, SSSD first makes a `(objectclass=*)` search, and glauth then closes the connection because it returns and error

https://github.com/glauth/glauth/blob/3e2e24cadb70ca419c822414a7092702b6280556/v2/pkg/handler/ldapopshelper.go#L240
Changing this line to return nil as error, just returns the desired resultcode without closing the connection

**Comment by Zen3515** [comment]
This issue exist since 2019, and now in 2022, is there any plan on fixing this?

**Comment by Fusion** [comment]
If you are using a client that requires reading the root DSE first, set `anonymousdse = true` in the backend configuration.

**Comment by Zen3515** [comment]
@Fusion Thanks, I found that out a few days ago and planning on document it in the SSSD guild. The minimum working example is actually not enough.

**Comment by Fusion** [comment]
I can believe that. I always find new things to add to the documentation... sigh!
